# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonitorPow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 829)
        MainWindow.setMinimumSize(QtCore.QSize(579, 829))
        MainWindow.setMaximumSize(QtCore.QSize(579, 829))
        MainWindow.setStyleSheet("background-color:white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 551, 721))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dataP = QtWidgets.QWidget()
        self.dataP.setObjectName("dataP")
        self.label = QtWidgets.QLabel(self.dataP)
        self.label.setGeometry(QtCore.QRect(170, 10, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dataP)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.dataP)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 531, 311))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../wska.PNG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.dataP)
        self.label_4.setGeometry(QtCore.QRect(100, 400, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.dataP)
        self.label_5.setGeometry(QtCore.QRect(80, 430, 411, 261))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../wyk.PNG"))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.dataP)
        self.mapP = QtWidgets.QWidget()
        self.mapP.setObjectName("mapP")
        self.label_6 = QtWidgets.QLabel(self.mapP)
        self.label_6.setGeometry(QtCore.QRect(0, 120, 551, 501))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../mapa.jpg"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.mapP)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.mapP)
        self.optionP = QtWidgets.QWidget()
        self.optionP.setObjectName("optionP")
        self.label_8 = QtWidgets.QLabel(self.optionP)
        self.label_8.setGeometry(QtCore.QRect(160, 260, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.optionP)
        self.mapBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mapBtn.setGeometry(QtCore.QRect(40, 760, 75, 23))
        self.mapBtn.setObjectName("mapBtn")
        self.dataBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dataBtn.setGeometry(QtCore.QRect(250, 760, 75, 23))
        self.dataBtn.setObjectName("dataBtn")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 760, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Dzisiaj jest \"dzień obecny\""))
        self.label_2.setText(_translate("MainWindow", "Jakość powietrz na dzień dzisiejszy"))
        self.label_4.setText(_translate("MainWindow", "Obecna stacja pomiarowa z okolocy: \"stacja\""))
        self.label_7.setText(_translate("MainWindow", "Mapa jakości powietrza"))
        self.label_8.setText(_translate("MainWindow", "strona w pracy"))
        self.mapBtn.setText(_translate("MainWindow", "Mapa"))
        self.dataBtn.setText(_translate("MainWindow", "Stacje/Dane"))
        self.pushButton_3.setText(_translate("MainWindow", "Opcje"))

